import uuid
from datetime import datetime, timezone, timedelta


def _d(days):
    return (datetime.now(timezone.utc) + timedelta(days=days)).strftime("%Y-%m-%d")


RAW = [
    ("India Foundation for the Arts – Arts Practice Grant", "India Foundation for the Arts", "Grant", ["Visual Arts", "Multi-disciplinary"], "Bengaluru, Karnataka", True, "Up to ₹10,00,000", 25, "Project grants for artists exploring new directions in their practice.", "IFA's Arts Practice programme supports practitioners to deepen enquiry within their own practice, take risks, and experiment. Grants cover project costs, artist fees and documentation over 12-18 months.", "Indian citizens, practising artists with at least 3 years of independent practice. Students not eligible.", ["Project proposal", "Portfolio", "Budget", "CV"], "None", "Hard", "Mid-career", "Foundation", ["funding", "project grant", "arts practice", "experimental"], True, "Emerging support available"),
    ("Khoj International Artists' Residency", "Khoj Studios", "Residency", ["Visual Arts", "Digital Art"], "New Delhi", False, "Studio + stipend ₹50,000", 12, "Six-week residency for experimental contemporary artists at Khoj Studios, Delhi.", "The Khoj residency offers studio space, curatorial support, materials budget and a public open-studio event. Artists working across media, installation, sound and performance are encouraged to apply.", "Open to Indian and South Asian artists aged 22+. Emerging and mid-career practitioners.", ["Portfolio", "Statement of intent", "CV"], "None", "Medium", "Emerging", "Residency", ["residency", "contemporary art", "delhi", "studio"], True, ""),
    ("National Scholarship for Young Artists", "Ministry of Culture, Government of India", "Scholarship", ["Music", "Dance", "Theatre", "Visual Arts", "Folk/Traditional Arts"], "Pan-India", False, "₹5,000/month for 2 years", 40, "Government scholarship for advanced training in performing and visual arts.", "The Scheme of Scholarships to Young Artistes supports training under gurus or in recognised institutions across Indian classical music, dance, theatre, visual arts and folk traditions.", "Indian nationals aged 18-25 with at least 5 years of training in their field.", ["Application form", "Training certificates", "Guru recommendation", "Age proof"], "None", "Medium", "Student", "Government", ["scholarship", "government", "training", "young artists"], True, ""),
    ("Serendipity Arts Festival Open Call", "Serendipity Arts Foundation", "Open Call", ["Multi-disciplinary", "Visual Arts", "Music", "Theatre"], "Goa", False, "Production support up to ₹8,00,000", 18, "Open call for new commissions at South Asia's largest multi-disciplinary arts festival.", "Serendipity Arts Festival invites proposals for new works across visual arts, music, dance, theatre, craft and culinary arts for its December edition in Panaji, Goa.", "Open to artists and collectives based in South Asia. Proposals for new or adapted works.", ["Proposal", "Portfolio", "Budget", "Technical rider"], "None", "Medium", "Any", "Festival", ["festival", "commission", "goa", "new work"], True, ""),
    ("Charles Wallace India Trust Arts Award", "Charles Wallace India Trust / British Council", "Fellowship", ["Visual Arts", "Writing", "Cultural Heritage"], "United Kingdom (from India)", False, "Fully funded UK residency + stipend", 55, "Fully funded fellowships for Indian artists and heritage professionals in the UK.", "CWIT grants enable artists, writers and heritage conservationists in the early-mid stage of their careers to spend time at UK institutions for research, residencies or professional development.", "Indian citizens residing in India, aged 25-45, with demonstrable professional achievement.", ["Application form", "Portfolio", "Two references", "Institutional invitation (preferred)"], "None", "Hard", "Mid-career", "International Organisation", ["international", "uk", "fellowship", "fully funded"], True, ""),
    ("Toto Funds the Arts – Music Award", "Toto Funds the Arts", "Award", ["Music"], "Pan-India", True, "₹1,00,000 cash award", 8, "Annual award recognising outstanding young Indian musicians and composers.", "TFA's music award honours original work by young musicians across genres — from indie and electronic to experimental and fusion. Winners receive a cash prize and mentorship connections.", "Indian citizens aged 18-29. Original compositions only.", ["3 original tracks", "Bio", "Statement"], "None", "Easy", "Emerging", "Foundation", ["award", "music", "young artists", "original work"], True, ""),
    ("Sangam House Writers' Residency", "Sangam House", "Residency", ["Writing"], "Bengaluru, Karnataka", False, "Room, board and workspace covered", 30, "International writing residency near Bengaluru for writers of all genres.", "Sangam House hosts writers from India and abroad for 2-4 week stays at Nrityagram. Fiction, non-fiction, poetry, translation and playwriting are all welcome.", "Writers with at least one published work or strong emerging portfolio. All languages welcome.", ["Writing sample", "Project description", "CV"], "None", "Medium", "Any", "Residency", ["writing", "residency", "literature", "translation"], True, ""),
    ("India Design Fellowship", "Godrej Design Lab", "Fellowship", ["Design"], "Mumbai, Maharashtra", True, "₹3,00,000 + mentorship", 22, "Fellowship supporting emerging Indian designers solving local problems through design.", "The fellowship funds designers working on furniture, product, social and sustainable design. Fellows receive funding, industry mentorship and a showcase platform.", "Indian designers under 35 with a working prototype or strong concept.", ["Concept note", "Portfolio", "Prototype images"], "None", "Medium", "Emerging", "CSR", ["design", "fellowship", "mentorship", "sustainability"], True, ""),
    ("Mumbai International Film Festival – Documentary Grant", "Films Division / MIFF", "Production Fund", ["Film"], "Mumbai, Maharashtra", False, "Up to ₹15,00,000 production support", 45, "Production funding for independent Indian documentary filmmakers.", "Supports documentary projects at production or post-production stage that tell urgent Indian stories. Selected projects premiere at MIFF.", "Indian filmmakers with at least one completed short or feature documentary.", ["Treatment", "Trailer/rough cut", "Budget", "Director's note"], "₹500", "Hard", "Mid-career", "Government", ["film", "documentary", "production fund", "miff"], True, ""),
    ("Jodhpur RIFF Folk Music Residency", "Jaipur Virasat Foundation", "Residency", ["Folk/Traditional Arts", "Music"], "Jodhpur, Rajasthan", False, "Travel, stay + ₹40,000 honorarium", 15, "Residency pairing folk musicians of Rajasthan with contemporary collaborators.", "Rajasthan International Folk Festival's residency invites musicians to collaborate with hereditary folk artists of Marwar, culminating in a live performance at Mehrangarh Fort.", "Musicians and composers with collaborative practice. Knowledge of folk traditions valued.", ["Music samples", "Collaboration proposal", "Bio"], "None", "Medium", "Any", "Festival", ["folk", "music", "rajasthan", "collaboration"], True, ""),
    ("FICA Emerging Artist Award", "Foundation for Indian Contemporary Art", "Award", ["Visual Arts"], "New Delhi", True, "₹5,00,000 + solo show", 28, "Annual award for an emerging Indian contemporary artist, with a solo exhibition.", "FICA's flagship award supports one emerging artist with production funds, mentoring and a curated solo exhibition at a leading Delhi gallery.", "Indian artists under 35 who have not yet had a major solo exhibition.", ["Portfolio (max 20 works)", "Artist statement", "CV", "Two references"], "None", "Medium", "Emerging", "Foundation", ["award", "contemporary art", "exhibition", "emerging"], True, ""),
    ("Zubaan Publishing Mentorship for Women Writers", "Zubaan Books", "Mentorship Programme", ["Writing"], "Pan-India", True, "6-month editorial mentorship", 20, "Mentorship programme for first-time women and non-binary writers from India.", "Zubaan pairs selected writers with senior editors to develop a book-length manuscript — fiction, memoir or narrative non-fiction — over six months.", "Women and non-binary writers, Indian residents, no prior book publication.", ["Writing sample (5,000 words)", "Synopsis", "Bio"], "None", "Easy", "Student", "Private Organisation", ["writing", "mentorship", "women", "publishing"], True, ""),
    ("Kochi-Muziris Biennale Students' Biennale Open Call", "Kochi Biennale Foundation", "Open Call", ["Visual Arts", "Digital Art"], "Kochi, Kerala", False, "Production + travel support", 35, "Open call for art students to exhibit at the Students' Biennale in Kochi.", "The Students' Biennale showcases work by art students from across South Asia alongside the main Kochi-Muziris Biennale, with curatorial mentorship and production support.", "Currently enrolled art students or graduates within 2 years from Indian institutions.", ["Portfolio", "Proposal", "Enrolment proof"], "None", "Easy", "Student", "Foundation", ["biennale", "students", "kochi", "exhibition"], True, ""),
    ("INTACH Heritage Research Fellowship", "INTACH", "Fellowship", ["Cultural Heritage", "Research", "Architecture"], "Pan-India", False, "₹40,000/month for 12 months", 50, "Research fellowships on India's tangible and intangible heritage.", "INTACH supports researchers documenting endangered heritage — crafts, architecture, oral traditions, historic settlements — leading to a publishable monograph.", "Postgraduates in relevant fields; heritage professionals with research aptitude.", ["Research proposal", "CV", "Writing sample", "Two references"], "None", "Hard", "Mid-career", "NGO", ["heritage", "research", "documentation", "fellowship"], True, ""),
    ("Prince Claus Seed Award (India)", "Prince Claus Fund", "Award", ["Multi-disciplinary", "Visual Arts", "Film", "Writing"], "International (open to India)", True, "€5,000 unrestricted", 42, "Unrestricted awards for emerging artists working on social themes.", "The Seed Awards support artists and cultural practitioners in the first 10 years of practice whose work engages pressing social issues in their communities.", "Artists from eligible countries including India, 2-10 years of practice.", ["Portfolio", "Motivation statement", "Two references"], "None", "Medium", "Emerging", "International Organisation", ["international", "unrestricted", "social practice", "award"], True, ""),
    ("Craft Innovation Grant – Handloom Futures", "Dastkar / CSR Consortium", "Grant", ["Craft", "Design"], "Pan-India", False, "₹2,50,000 + market access", 17, "Grants for craftsperson-designer collaborations reimagining Indian handloom.", "Funds collaborative projects between designers and weaving clusters to develop new products, with exhibition at Dastkar bazaars and buyer connect.", "Designer-artisan teams; at least one member from a recognised craft cluster.", ["Joint proposal", "Cluster details", "Product sketches", "Budget"], "None", "Medium", "Any", "NGO", ["craft", "handloom", "collaboration", "grant"], True, ""),
    ("NFDC Screenwriters' Lab", "National Film Development Corporation", "Fellowship", ["Film", "Writing"], "Mumbai, Maharashtra", True, "Lab + international mentorship", 26, "Script development lab for Indian feature film writers with global mentors.", "NFDC's lab selects feature screenplays for intensive development with international script consultants, ending in a co-production market pitch.", "Indian citizens with a feature-length screenplay draft in any Indian language or English.", ["Screenplay draft", "Synopsis", "Writer's statement", "Bio"], "₹1,000", "Hard", "Mid-career", "Government", ["film", "screenwriting", "lab", "nfdc"], True, ""),
    ("Gender Bender Grant", "Sandbox Collective & Goethe-Institut", "Grant", ["Multi-disciplinary", "Theatre", "Digital Art", "Dance"], "Bengaluru, Karnataka", True, "₹75,000 per project", 10, "Grants for new artistic works on gender, exhibited at the Gender Bender festival.", "Supports experimental works across any medium that engage with gender, culminating in a public showing in Bengaluru.", "Open to Indian residents, all disciplines, all career stages.", ["Concept note", "Budget", "Portfolio"], "None", "Easy", "Any", "Private Organisation", ["gender", "experimental", "festival", "grant"], True, ""),
    ("Photography South Asia Grant", "Murthy NAYAK Foundation", "Grant", ["Photography"], "Pan-India", True, "$3,000 project grant", 33, "Project grant for documentary photographers working in South Asia.", "Supports long-form documentary photography projects in South Asia, with mentorship from senior photographers and publication support.", "Photographers from or working in South Asia; emerging and mid-career.", ["20-image portfolio", "Project statement", "Budget"], "None", "Medium", "Emerging", "Foundation", ["photography", "documentary", "grant", "south asia"], True, ""),
    ("Ratan Tata Trust Performing Arts Support", "Sir Ratan Tata Trust", "Grant", ["Theatre", "Dance", "Music"], "Pan-India", False, "Up to ₹6,00,000", 60, "Institutional and individual support for India's performing arts ecosystems.", "Supports productions, training initiatives and archival projects in theatre, dance and music, prioritising underserved regions and traditions.", "Registered organisations and individual practitioners with 5+ years in the field.", ["Proposal", "Budget", "Track record", "References"], "None", "Hard", "Established", "Foundation", ["performing arts", "institutional", "grant", "trust"], True, ""),
    ("Vimeo x Dharamshala Short Film Commission", "Dharamshala International Film Festival", "Commission", ["Film"], "Dharamshala, Himachal Pradesh", True, "₹4,00,000 production budget", 14, "Commission for a short film premiering at DIFF, on the theme 'Mountains and Memory'.", "DIFF commissions one filmmaker to create a short (under 20 min) responding to Himalayan landscapes and communities, premiering at the festival.", "Indian filmmakers with at least one completed short film.", ["Concept", "Previous work links", "Budget", "Timeline"], "None", "Medium", "Emerging", "Festival", ["film", "commission", "short film", "himalaya"], True, ""),
    ("Asia Society India Arts Fellowship", "Asia Society India Centre", "Fellowship", ["Visual Arts", "Research", "Cultural Heritage"], "Mumbai, Maharashtra", False, "₹1,50,000 + public programme", 38, "Fellowship for research-driven artistic projects on Asia's shared cultures.", "Fellows develop a research-based project over six months with access to Asia Society's network, presenting at a public programme in Mumbai.", "Indian artists, curators and researchers, 3+ years of practice.", ["Research proposal", "CV", "Portfolio"], "None", "Medium", "Mid-career", "International Organisation", ["research", "fellowship", "asia", "curatorial"], True, ""),
    ("Unbox Cultural Futures Grant", "Unbox Festival / Quicksand", "Grant", ["Design", "Digital Art", "Multi-disciplinary"], "Bengaluru, Karnataka", True, "₹2,00,000 per project", 24, "Grants for speculative design and art projects imagining India's cultural futures.", "Supports interdisciplinary teams creating installations, games, films or experiences that speculate on future Indian cultures, shown at Unbox Festival.", "Open to designers, artists and technologists in India. Teams encouraged.", ["Concept deck", "Team bios", "Budget"], "None", "Medium", "Any", "Festival", ["speculative design", "futures", "interdisciplinary", "festival"], True, ""),
    ("Kala Ghoda Emerging Sculptor Award", "Kala Ghoda Association", "Award", ["Visual Arts", "Craft"], "Mumbai, Maharashtra", False, "₹1,00,000 + public installation", 5, "Award for an emerging sculptor to create a public installation at Kala Ghoda Arts Festival.", "The winning proposal is fabricated and installed in the Kala Ghoda precinct during the festival, seen by over a million visitors.", "Sculptors under 40 based in India. Public-safe, weather-proof proposals only.", ["Maquette photos", "Proposal", "Fabrication plan"], "None", "Medium", "Emerging", "Festival", ["sculpture", "public art", "mumbai", "installation"], True, ""),
    ("Sahapedia Digital Humanities Fellowship", "Sahapedia", "Fellowship", ["Research", "Cultural Heritage", "Digital Art"], "Pan-India", True, "₹30,000/month for 6 months", 47, "Fellowships to document Indian cultural knowledge for an open digital encyclopedia.", "Fellows research and produce multimedia modules — essays, video, interactive maps — on Indian art forms, monuments and living traditions.", "Postgraduates or practitioners in humanities, arts or media. Fluency in one Indian language besides English preferred.", ["Proposal", "Writing sample", "CV"], "None", "Medium", "Student", "NGO", ["digital humanities", "documentation", "research", "fellowship"], True, ""),
    ("British Council India-UK Music Exchange", "British Council", "Travel Grant", ["Music"], "United Kingdom (from India)", False, "Travel + per diem, fully covered", 52, "Travel grants for Indian musicians to collaborate and perform in the UK.", "Supports showcases, co-writing camps and festival appearances in the UK for Indian independent musicians, with visa and travel support.", "Indian musicians/bands with professional releases and live experience.", ["EPK", "Music links", "Invitation or plan", "Passport copy"], "None", "Medium", "Mid-career", "International Organisation", ["travel grant", "music", "uk", "showcase"], True, ""),
    ("Design X Social Impact Challenge", "IDC IIT Bombay & UNDP", "Competition", ["Design"], "Pan-India", True, "₹5,00,000 prize pool", 19, "National design competition for solutions to social and environmental challenges.", "Student and professional tracks invite design concepts addressing accessibility, climate and public health, judged by an international jury.", "Open to Indian residents; separate student and professional categories.", ["Entry boards", "Concept video (2 min)", "Team details"], "₹300", "Easy", "Any", "University", ["competition", "social impact", "design", "prize"], True, ""),
    ("Attakkalari Dance Residency", "Attakkalari Centre for Movement Arts", "Residency", ["Dance"], "Bengaluru, Karnataka", False, "Studio + ₹60,000 stipend", 29, "Choreographic residency for contemporary movement artists at Attakkalari.", "An 8-week residency to develop new choreographic work with dramaturgical support, technical residency week and work-in-progress showing.", "Contemporary dancers/choreographers with 3+ years of practice.", ["Video links of past work", "Concept note", "CV"], "None", "Medium", "Mid-career", "Residency", ["dance", "choreography", "residency", "movement"], True, ""),
    ("Tata Literature Live! First Book Award", "Tata Literature Live!", "Award", ["Writing"], "Pan-India", True, "₹1,00,000 + festival platform", 65, "Award for the best debut book by an Indian author, fiction and non-fiction.", "Recognises outstanding first books published in the eligibility year, with categories for fiction and non-fiction, presented at the Mumbai festival.", "Debut books by Indian citizens published in the last 12 months. Publisher or self nomination.", ["Published book copies", "Nomination form"], "None", "Easy", "Emerging", "Festival", ["literature", "debut", "award", "book"], True, ""),
    ("Goa Affordable Art Fest Open Call", "Goa Affordable Art Fest", "Open Call", ["Visual Arts", "Photography", "Digital Art"], "Goa", False, "Exhibition + sales platform", 9, "Open call for affordable original artworks to exhibit and sell in Goa.", "Artists exhibit works priced under ₹50,000 to a wide collector base, with the fest handling display, sales and promotion.", "Artists residing in India. Original works only, priced under ₹50,000.", ["Work images", "Price list", "Bio"], "₹750", "Easy", "Any", "Gallery", ["exhibition", "sales", "affordable art", "goa"], False, ""),
    ("Archaeology of Sound – Audio Art Commission", "Indian Sonic Research Organisation", "Commission", ["Music", "Digital Art", "Research"], "Pan-India", True, "₹1,75,000 per commission", 21, "Commissions for sound art exploring India's acoustic histories.", "ISRO (sonic) commissions audio works — field recording compositions, installations, radio art — exploring disappearing soundscapes of India.", "Sound artists, musicians and radio producers based in India.", ["Audio samples", "Concept", "Technical needs"], "None", "Medium", "Any", "Private Organisation", ["sound art", "commission", "audio", "experimental"], False, ""),
    ("Habitat Photosphere Public Art Grant", "India Habitat Centre", "Grant", ["Photography", "Visual Arts"], "New Delhi", False, "₹3,00,000 production", 36, "Grant for lens-based public art in Delhi's Habitat Centre precinct.", "Supports large-format photographic installations engaging public audiences, displayed for three months at IHC.", "Lens-based artists with exhibition history. Delhi-feasible installs.", ["Portfolio", "Site proposal", "Budget"], "None", "Medium", "Mid-career", "Museum", ["photography", "public art", "delhi", "installation"], True, ""),
    ("Kabir Festival Storytelling Open Call", "Kabir Festival Mumbai", "Open Call", ["Folk/Traditional Arts", "Music", "Theatre"], "Mumbai, Maharashtra", False, "Performance fee + travel", 11, "Open call for folk performances rooted in Bhakti and Sufi traditions.", "The festival curates baithaks, concerts and storytelling sessions across Mumbai celebrating Kabir and syncretic traditions.", "Folk musicians, storytellers and theatre groups practising Bhakti/Sufi repertoire.", ["Performance video", "Repertoire list", "Tech needs"], "None", "Easy", "Any", "Festival", ["folk", "bhakti", "performance", "mumbai"], True, ""),
    ("Young Architects Festival Award", "Council of Architecture / YAF", "Award", ["Architecture"], "Pan-India", True, "₹2,00,000 + publication", 44, "National award for built and unbuilt work by young Indian architects.", "Recognises design excellence in projects by architects under 40 — built works, competitions and research, published in a national catalogue.", "Registered architects under 40 practising in India.", ["Project portfolio", "Drawings", "Registration proof"], "₹1,500", "Medium", "Emerging", "University", ["architecture", "award", "young architects", "publication"], True, ""),
    ("Indian Ocean Craft Triennial Travel Grant", "Crafts Council of India", "Travel Grant", ["Craft", "Folk/Traditional Arts"], "International (from India)", False, "Travel + stay fully covered", 58, "Travel grants for Indian craftspeople to exhibit at the Indian Ocean Craft Triennial.", "Covers travel, freight and accommodation for master artisans presenting at the triennial, with interpreter support.", "Practising artisans nominated by craft organisations or self-nominated with portfolio.", ["Craft portfolio", "Nomination letter", "Passport copy"], "None", "Medium", "Established", "NGO", ["craft", "travel", "international", "artisan"], True, ""),
    ("Mud on Boots Environmental Art Project", "Sanctuary Nature Foundation", "Grant", ["Visual Arts", "Photography", "Film"], "Pan-India", False, "₹2,00,000 over 1 year", 32, "Support for artists documenting conservation stories from India's wild spaces.", "Funds year-long art and media projects embedded with conservation efforts, from wildlife photography to community murals.", "Artists and filmmakers willing to work in field conditions with conservationists.", ["Proposal", "Portfolio", "Field plan"], "None", "Medium", "Any", "NGO", ["environment", "conservation", "documentation", "grant"], False, ""),
    ("Ranga Shankara Theatre Directors' Lab", "Ranga Shankara", "Mentorship Programme", ["Theatre"], "Bengaluru, Karnataka", False, "Lab + production slot", 27, "Intensive lab for emerging theatre directors with veteran mentors.", "Selected directors workshop a full production concept over 3 months, with the best receiving a production slot in Ranga Shankara's season.", "Theatre directors under 35 with at least two directed productions.", ["Production portfolio", "Concept note", "Two references"], "None", "Medium", "Emerging", "Private Organisation", ["theatre", "directing", "lab", "mentorship"], True, ""),
    ("Digital Art x AI Open Studio", "Nature Morte & Terrain.art", "Open Call", ["Digital Art"], "New Delhi", True, "Exhibition + ₹1,00,000 honorarium", 16, "Open call for new-media and AI-assisted artworks for a Delhi gallery show.", "Seeking generative, interactive and AI-collaborative works interrogating technology's role in Indian visual culture.", "New media artists based in India. Works must be exhibition-ready.", ["Work documentation", "Technical specs", "Statement"], "None", "Medium", "Any", "Gallery", ["digital art", "ai", "new media", "exhibition"], False, ""),
    ("Kalakriti Emerging Printmaker Residency", "Kalakriti Art Gallery", "Residency", ["Visual Arts", "Craft"], "Hyderabad, Telangana", False, "Studio, materials + ₹35,000", 41, "Printmaking residency with master printers at Kalakriti's Hyderabad studio.", "A 4-week residency with access to etching, lithography and serigraphy facilities, closing with a portfolio exhibition.", "Printmakers and visual artists, fine arts degree or equivalent practice.", ["Portfolio", "Statement", "CV"], "None", "Easy", "Emerging", "Gallery", ["printmaking", "residency", "hyderabad", "studio"], True, ""),
    ("Science Gallery Bengaluru – Art-Science Commission", "Science Gallery Bengaluru", "Commission", ["Multi-disciplinary", "Digital Art", "Research"], "Bengaluru, Karnataka", True, "₹6,00,000 commission", 49, "Commission for art-science works for the gallery's upcoming themed season.", "Commissions artists collaborating with scientists to create installations for a public exhibition on the theme of 'WATER'.", "Artists and collectives; scientific collaboration required or facilitated.", ["Concept", "Portfolio", "Collaboration plan", "Budget"], "None", "Hard", "Mid-career", "Museum", ["art-science", "commission", "installation", "research"], True, ""),
    ("Rural Arts Outreach Fellowship", "SPIC MACAY", "Fellowship", ["Music", "Dance", "Folk/Traditional Arts"], "Pan-India", False, "₹25,000/month + travel", 23, "Fellowship to take classical and folk arts to rural schools across India.", "Fellows organise baithaks and workshops by master artists in rural schools, documenting impact over a 10-month cycle.", "Graduates passionate about arts education; travel-heavy role.", ["Statement of purpose", "CV", "References"], "None", "Easy", "Student", "NGO", ["outreach", "education", "classical arts", "fellowship"], True, ""),
    ("Emami Art Experimental Film Fund", "Emami Art, Kolkata", "Production Fund", ["Film", "Digital Art"], "Kolkata, West Bengal", True, "₹3,50,000 per project", 37, "Production fund for experimental and artists' moving image works.", "Supports experimental film and video art production, with premiere screening at Emami Art and distribution advice.", "Artists and filmmakers from India working in experimental moving image.", ["Previous work", "Treatment", "Budget"], "None", "Medium", "Any", "Gallery", ["experimental film", "video art", "kolkata", "production"], False, ""),
    ("Heritage Walk Design Challenge", "Ahmedabad Municipal Corporation", "Competition", ["Architecture", "Design", "Cultural Heritage"], "Ahmedabad, Gujarat", False, "₹1,50,000 + implementation", 6, "Competition to redesign heritage walk experiences in Ahmedabad's old city.", "Seeking wayfinding, signage and experience design proposals for the UNESCO World Heritage city walk routes.", "Designers and architects; site visit mandatory before submission.", ["Design boards", "Concept note", "Team profile"], "None", "Medium", "Any", "Government", ["heritage", "urban design", "competition", "ahmedabad"], True, ""),
    ("Contemporary Clay Biennale Open Call", "Indian Ceramics Triennale", "Open Call", ["Craft", "Visual Arts"], "Jaipur, Rajasthan", False, "Production support + freight", -5, "Open call for ceramic artists for the Indian Ceramics Triennale in Jaipur.", "India's premier clay art platform invites proposals for ambitious ceramic installations and new work.", "Ceramic artists worldwide; Indian artists strongly encouraged.", ["Proposal", "Portfolio", "Technical requirements"], "None", "Medium", "Any", "Festival", ["ceramics", "triennale", "jaipur", "clay"], True, ""),
    ("City as Studio Urban Art Grant", "St+art India Foundation", "Grant", ["Visual Arts", "Design"], "Multiple cities, India", False, "₹2,50,000 + wall + crew", -12, "Grants for muralists and street artists to create public works in Indian cities.", "St+art India provides walls, permissions, lifts and crew for large-scale public murals in Delhi, Mumbai and Hyderabad districts.", "Muralists and street artists with demonstrated large-scale work.", ["Mural portfolio", "Concept sketch", "Availability"], "None", "Medium", "Emerging", "Foundation", ["street art", "mural", "public art", "urban"], True, ""),
    ("Translation Fellowship for Indian Languages", "New India Foundation", "Fellowship", ["Writing", "Research"], "Pan-India", True, "₹6,00,000 over 18 months", 70, "Fellowships for translating significant non-fiction between Indian languages.", "Supports translators bringing important works of Indian non-fiction into and between Indian languages, with editorial support and publication.", "Translators with published work; language pair must include an Indian language.", ["Sample translation", "Proposal", "Rights status", "CV"], "None", "Hard", "Mid-career", "Foundation", ["translation", "languages", "non-fiction", "fellowship"], True, ""),
]


def get_seed_opportunities():
    now = datetime.now(timezone.utc).isoformat()
    opps = []
    for i, r in enumerate(RAW):
        (title, org, otype, disciplines, location, online, funding, dl_offset, summary,
         description, eligibility, docs, fee, difficulty, stage, source_type, tags, verified, note) = r
        opps.append({
            "id": str(uuid.uuid4()),
            "title": title,
            "organisation": org,
            "opportunity_type": otype,
            "disciplines": disciplines,
            "location": location,
            "online_available": online,
            "funding_amount": funding,
            "deadline": _d(dl_offset),
            "summary": summary,
            "description": description,
            "eligibility": eligibility,
            "required_documents": docs,
            "application_fee": fee,
            "difficulty": difficulty,
            "career_stage": stage,
            "source_url": f"https://example.org/opportunities/{i+1}",
            "source_type": source_type,
            "tags": tags,
            "verified": verified,
            "status": "published",
            "created_at": now,
            "updated_at": now,
        })
    return opps
